#!/bin/sh

remote=$1
_target=${remote//\//.}
target=${_target//:/.}
status=$(cat $target.status)

echo remote : $remote
echo target : $target
echo status : $status

if test "x$status" = "xok"; then
	echo already done
	exit 0;
fi

if test -f $target.work_pid; then
	echo pid $(cat $target.work_pid) already working
	exit 1;
fi

(
	flock 9 || exit 1;

	function run_git () {
		target=$1
		shift

		cmd="$*"
		echo cmd: $cmd
		$cmd 2>&1 >/dev/null | sed -u 's//\n/g' | while IFS= read line; do
			echo $line > $target.status
		done
	}

	echo clean > $target.status
	rm -Rf $target
	echo clone > $target.status
	if run_git $target git clone --progress --mirror $remote $target; then
		echo ok > $target.status
		echo $remote > $target.origin
	else
		echo clone failed > $target.status
	fi
) 9>./$target.long_lock &
