#!/bin/sh

remote=$1
_target=${remote//\//.}
target=${_target//:/.}
status=$(cat $target.status)

echo remote : $remote
echo target : $target
echo status : $status

if test -f $target.work_pid; then
	echo pid $(cat $target.work_pid) already working
	exit 1;
fi

echo $$ > $target.work_pid

(
	flock 9 || exit 1;

	function run_git () {
		target=$1
		shift

		cmd="$*"
		echo cmd: $cmd
		( cd $target && $cmd 2>&1 >/dev/null; ) | sed -u 's//\n/g' | while IFS= read line; do
			echo $line > $target.status
		done
	}

	echo fetch > $target.status
	if run_git $target git fetch --progress origin; then
		echo ok > $target.status
		echo $remote > $target.origin
	else
		echo fetch failed > $target.status
	fi

	rm $target.work_pid
) 9>./$target.long_lock &
